from pathlib import Path
path = Path('/home/ubuntu/devora-frontend/client/src/pages/Home.tsx')
text = path.read_text()
text = text.replace('import { defaultSkillProfile, parseSkillProfile, type SkillProfile } from "@/lib/devoraMockData";', 'import { defaultSkillProfile, parseSkillProfile, personalizeModules, type SkillProfile } from "@/lib/devoraMockData";')
text = text.replace('  const currentModule = modules[selectedModule];', '  const modulePlan = useMemo(() => personalizeModules(twinProfile), [twinProfile]);\n  const currentModule = modulePlan[selectedModule] ?? modulePlan[0];')
text = text.replace('<Dashboard role={role!} title={title}', '<Dashboard role={role!} modulePlan={modulePlan} title={title}')
text = text.replace('<LearningPath onAssessment={() => setView("twin")} selectedModule={selectedModule}', '<LearningPath onAssessment={() => setView("twin")} modulePlan={modulePlan} selectedModule={selectedModule}')
text = text.replace('function Dashboard({ role, title, onProject, onView, onModule, onTwin, onHeatmap, onAdminMember }: { role: Role; title: string;', 'function Dashboard({ role, modulePlan, title, onProject, onView, onModule, onTwin, onHeatmap, onAdminMember }: { role: Role; modulePlan: ReturnType<typeof personalizeModules>; title: string;')
text = text.replace('<DeveloperDashboard onView={onView} onModule={onModule} onTwin={onTwin} />', '<DeveloperDashboard modulePlan={modulePlan} onView={onView} onModule={onModule} onTwin={onTwin} />')
text = text.replace('function DeveloperDashboard({ onView, onModule, onTwin }: { onView: (view: View) => void; onModule: () => void; onTwin: () => void }) {', 'function DeveloperDashboard({ modulePlan, onView, onModule, onTwin }: { modulePlan: ReturnType<typeof personalizeModules>; onView: (view: View) => void; onModule: () => void; onTwin: () => void }) {')
text = text.replace('modules.slice(0, 3).map((module)', 'modulePlan.slice(0, 3).map((module)')
text = text.replace('function LearningPath({ onAssessment, selectedModule,', 'function LearningPath({ onAssessment, modulePlan, selectedModule,')
text = text.replace('{ onAssessment: () => void; selectedModule: number;', '{ onAssessment: () => void; modulePlan: ReturnType<typeof personalizeModules>; selectedModule: number;')
text = text.replace('  const mod = modules[selectedModule];', '  const mod = modulePlan[selectedModule] ?? modulePlan[0];')
text = text.replace('modules.map((item, index)', 'modulePlan.map((item, index)')
text = text.replace('module.status === "complete" ? <Check size={15} /> : module.status === "locked" ? <LockKeyhole size={14} /> : module.tag', 'module.status === "complete" || module.status === "skipped" ? <Check size={15} /> : module.status === "locked" ? <LockKeyhole size={14} /> : module.tag')
text = text.replace('module.status === "complete" ? <Check size={15} /> : module.status === "locked" ? <LockKeyhole size={14} /> : module.tag', 'module.status === "complete" || module.status === "skipped" ? <Check size={15} /> : module.status === "locked" ? <LockKeyhole size={14} /> : module.tag')
text = text.replace('module.status}</small>', 'module.status === "skipped" ? "Shortened" : module.status}</small>')
path.write_text(text)
print('personalized module rendering patch applied')
