"use client";
import { useState } from "react";
import { ChevronDown, ChevronRight, ChevronLeft, LockKeyhole, Radio, ShieldCheck, Terminal, UserRound, Database, GitBranch, Bot } from "lucide-react";
import { credentials } from "../lib/data";
import { login, setSession } from "../lib/auth";
import { useRouter } from "next/navigation";

export function Portal(){
 const router=useRouter();const [step,setStep]=useState<"landing"|"auth">("landing");const [id,setId]=useState("");const [password,setPassword]=useState("");const [busy,setBusy]=useState(false);const [error,setError]=useState("");const [open,setOpen]=useState(false);const [log,setLog]=useState(["[SYS] DEVORA secure terminal online","[SYS] waiting for identity packet..."]);
 const submit=async(e:React.FormEvent)=>{e.preventDefault();setError("");setBusy(true);setLog(v=>[...v,"[AUTH] decrypting identity packet..."]);try{const s=await login(id,password);setSession(s);setLog(v=>[...v,"[AUTH] identity verified","[SYS] routing to command center..."]);router.push("/cockpit")}catch(err){setError((err as Error).message);setLog(v=>[...v,"[ERR] AUTH_FAILURE // packet rejected"])}finally{setBusy(false)}};
 const quick=(x:typeof credentials[number])=>{setId(x.id);setPassword(x.password);setError("")};
 return <main className="cyber-bg scanline flex min-h-screen items-center justify-center px-4 py-5 sm:px-6 lg:px-8"><div className="relative z-10 w-full max-w-6xl overflow-hidden rounded-[28px] border border-white/10 bg-[#071820]/80 shadow-[0_30px_120px_rgba(0,0,0,.55)] backdrop-blur-2xl">
  {step==="landing"
   ?<Landing onContinue={()=>setStep("auth")}/>
   :<Auth onBack={()=>setStep("landing")} id={id} password={password} setId={setId} setPassword={setPassword} busy={busy} error={error} submit={submit} open={open} setOpen={setOpen} quick={quick} log={log}/>}
 </div></main>
}

function Landing({onContinue}:{onContinue:()=>void}){
 return <section className="relative flex flex-col items-center justify-center overflow-hidden px-6 py-8 text-center sm:px-12 sm:py-10"><div className="absolute -left-24 top-10 h-72 w-72 rounded-full bg-teal-600/10 blur-3xl"/><div className="absolute -right-20 bottom-0 h-80 w-80 rounded-full bg-cyan-500/10 blur-3xl"/><div className="relative flex max-w-2xl flex-col items-center">
  <div className="flex items-center gap-3"><div className="h-11 w-11 shrink-0 overflow-hidden rounded-xl border border-cyan-300/25 shadow-[0_0_20px_rgba(94,234,212,.22)]"><img src="/devora-logo.png" alt="DEVORA" className="h-full w-full object-cover"/></div><div className="text-left"><img src="/devora-title.png" alt="DEVORA" className="h-5 w-auto sm:h-6"/><div className="mt-1 text-[8px] tracking-[.34em] text-cyan-300/60">DEVELOPER KNOWLEDGE SYSTEM</div></div></div>
  <div className="mt-6 flex items-center gap-2 text-[10px] font-bold uppercase tracking-[.32em] text-teal-200"><Radio size={13}/> AI-powered developer onboarding</div>
  <h1 className="text-glow mt-3 text-3xl font-bold leading-[1.08] tracking-[-.03em] text-white sm:text-4xl lg:text-5xl">Turn any <span className="text-cyan-300">codebase</span> into a learning journey.</h1>
  <p className="mt-4 max-w-lg text-sm leading-6 text-slate-400 sm:text-base">DEVORA connects repository intelligence, project documentation, grounded answers and adaptive learning into one developer command center.</p>
  <div className="relative mt-6 grid w-full max-w-xl grid-cols-2 gap-3 sm:grid-cols-4">{[[GitBranch,"REPOSITORY"],[Database,"KNOWLEDGE"],[ShieldCheck,"LEARNING"],[Bot,"BOB"]].map(([Icon,label])=><div key={label as string} className="glass rounded-xl p-3"><Icon size={14} className="mx-auto text-cyan-300"/><div className="mt-2 text-[8px] font-bold tracking-[.18em] text-slate-500">{label as string}</div></div>)}</div>
  <button onClick={onContinue} className="group relative mt-8 flex h-12 items-center justify-center gap-3 overflow-hidden rounded-xl border border-teal-200/35 bg-gradient-to-r from-teal-600 to-cyan-500 px-9 text-xs font-black tracking-[.17em] text-white shadow-[0_0_35px_rgba(121,222,213,.16)] transition hover:-translate-y-0.5 hover:shadow-[0_0_50px_rgba(34,211,238,.22)]">SIGN IN / SIGN UP <ChevronRight size={16}/></button>
 </div></section>
}

function Auth({onBack,id,password,setId,setPassword,busy,error,submit,open,setOpen,quick,log}:{onBack:()=>void;id:string;password:string;setId:(v:string)=>void;setPassword:(v:string)=>void;busy:boolean;error:string;submit:(e:React.FormEvent)=>void;open:boolean;setOpen:React.Dispatch<React.SetStateAction<boolean>>;quick:(x:typeof credentials[number])=>void;log:string[]}){
 return <section className="mx-auto flex w-full max-w-lg flex-col justify-center px-6 py-8 sm:px-10 sm:py-10">
  <button onClick={onBack} className="mb-4 flex w-fit items-center gap-1.5 text-[9px] font-bold uppercase tracking-[.2em] text-slate-500 transition hover:text-cyan-300"><ChevronLeft size={13}/> Back</button>
  <div className="mb-5 flex items-start justify-between gap-4"><div><div className="mb-1.5 flex items-center gap-2 text-[9px] font-bold uppercase tracking-[.3em] text-cyan-300"><ShieldCheck size={13}/> Secure Access Portal</div><h2 className="text-2xl font-bold text-white sm:text-3xl">Initialize your session.</h2><p className="mt-1.5 text-sm text-slate-500">Authenticate to enter the developer cockpit.</p></div><span className="rounded-full border border-emerald-300/20 bg-emerald-300/5 px-3 py-1.5 text-[8px] font-black tracking-widest text-emerald-300">SECURE</span></div>
  {error&&<div className="mb-4 flex gap-3 rounded-xl border border-red-400/20 bg-red-400/5 p-3 font-mono text-[10px] leading-5 text-red-300"><Terminal size={14} className="mt-0.5 shrink-0"/>{error}</div>}
  <form onSubmit={submit} className="space-y-4"><Field label="Username / ID" icon={<UserRound size={14}/>} value={id} onChange={setId} placeholder="e.g. ankita"/><Field label="Access Key" icon={<LockKeyhole size={14}/>} value={password} onChange={setPassword} placeholder="••••••••••" type="password"/><button disabled={busy||!id||!password} className="group relative flex h-12 w-full items-center justify-center gap-3 overflow-hidden rounded-xl border border-teal-200/35 bg-gradient-to-r from-teal-600 to-cyan-500 text-xs font-black tracking-[.17em] text-white shadow-[0_0_35px_rgba(121,222,213,.16)] transition hover:shadow-[0_0_50px_rgba(34,211,238,.2)] disabled:cursor-not-allowed disabled:opacity-40">{busy?<><Terminal size={16} className="animate-decrypt"/> DECRYPTING IDENTITY...</>:<>INITIALIZE SESSION <ChevronRight size={17}/></>}</button></form>
  <div className="mt-5 overflow-hidden rounded-2xl border border-white/8 bg-black/20"><button onClick={()=>setOpen(v=>!v)} className="flex w-full items-center justify-between p-3.5 text-left"><span><span className="block text-[10px] font-black uppercase tracking-[.2em] text-slate-300">Credentials Reference Sheet</span><span className="mt-1 block text-[10px] text-slate-600">Quick-fill demo identities for local testing</span></span>{open?<ChevronDown size={16}/>:<ChevronRight size={16}/>}</button>{open&&<div className="max-h-[200px] overflow-y-auto border-t border-white/8 p-3">{credentials.map(c=><button key={c.id} onClick={()=>quick(c)} className="mb-2 flex w-full items-center justify-between rounded-xl border border-white/5 bg-white/[.02] p-3 text-left transition last:mb-0 hover:border-cyan-300/25 hover:bg-cyan-300/[.04]"><span><span className="block text-xs font-bold text-white">{c.name}</span><span className="font-mono text-[9px] text-cyan-300/70">{c.id}</span></span><span className="text-[8px] uppercase tracking-widest text-slate-600">{c.role}</span></button>)}</div>}</div>
  <div className="mt-4 flex items-center gap-2 font-mono text-[9px] text-slate-700"><Terminal size={11}/><span className="truncate">{log[log.length-1]}</span></div>
 </section>
}

function Field({label,icon,value,onChange,placeholder,type="text"}:{label:string;icon:React.ReactNode;value:string;onChange:(v:string)=>void;placeholder:string;type?:string}){return <label className="block"><span className="mb-1.5 flex items-center gap-2 text-[9px] font-bold uppercase tracking-[.2em] text-slate-500">{icon}{label}</span><input required type={type} value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder} className="h-12 w-full rounded-xl border border-white/10 bg-[#081a22]/80 px-4 font-mono text-sm text-white outline-none transition placeholder:text-slate-700 focus:border-cyan-300/45 focus:bg-cyan-300/[.02] focus:shadow-[0_0_28px_rgba(34,211,238,.1)]"/></label>}
