// Signal Garden surface: a premium, evidence-led developer profile that turns onboarding context into an evolving Twin.
import { ArrowUpRight, BrainCircuit, ChevronRight, FileText, Sparkles, Target, Upload } from "lucide-react";
import { useMemo } from "react";
import { buildTwin, defaultSkillProfile, type SkillProfile } from "@/lib/devoraMockData";

export default function DeveloperTwin({ profile = defaultSkillProfile, assessmentComplete = false, onLearningPath }: { profile?: SkillProfile; assessmentComplete?: boolean; onLearningPath?: () => void }) {
  const twin = useMemo(() => buildTwin(profile, assessmentComplete), [profile, assessmentComplete]);
  return <div className="twin-page">
    <div className="page-heading twin-heading"><div><p className="eyebrow seafoam">DEVELOPER INTELLIGENCE / {assessmentComplete ? "EVOLVING" : "PROFILE IMPORTED"}</p><h1>Developer Twin</h1><p>A living profile of what you know, what to learn next, and how your project context changes the route.</p></div></div>
    <section className="twin-hero-grid"><div className="twin-score-card"><div className="twin-score-orbit"><span>{twin.overall}</span><small>twin score</small></div><div><span className="eyebrow">YOUR SIGNAL</span><h2>{assessmentComplete ? "Bob has updated your Twin." : "Your Twin is taking shape."}</h2><p>{assessmentComplete ? "Your Twin is updated from Bob’s assessment read." : twin.signal}</p><div className="twin-source-row"><span><Upload size={13} /> {profile.fileName}</span><span><FileText size={13} /> REPO + COMPANY DOCS</span></div></div></div><div className="twin-focus-card"><div className="section-head"><div><span className="eyebrow">NEXT BEST FOCUS</span><h3>{assessmentComplete ? "Keep the signal moving" : twin.gaps[0].label}</h3></div><Target size={18} /></div><p>{assessmentComplete ? "Bob’s read is complete. Continue through the learning path to turn the next gap into practical confidence." : "A focused module can turn this gap into confident project fluency."}</p>{onLearningPath && <button className="text-btn" onClick={onLearningPath}>Return to learning path <ArrowUpRight size={14} /></button>}</div></section>
    <section className="twin-grid"><div className="twin-panel"><div className="section-head"><div><span className="eyebrow">STRENGTHS</span><h3>What you bring in</h3></div><Sparkles size={17} /></div><div className="twin-bars">{twin.strengths.map((item) => <div className="twin-bar" key={item.label}><div><span>{item.label}</span><b>{item.score}%</b></div><span className="twin-track"><i style={{ width: `${item.score}%`, background: item.color }} /></span></div>)}</div></div><div className="twin-panel gap-panel"><div className="section-head"><div><span className="eyebrow">KNOWLEDGE GAPS</span><h3>Where the path adapts</h3></div></div>{twin.gaps.map((item) => <div className="gap-row" key={item.label}><div><strong>{item.label}</strong><small>{item.delta}</small></div><span>{item.score}%</span></div>)}</div></section>
    <section className="twin-evolution"><div className="section-head"><div><span className="eyebrow">TWIN EVOLUTION</span><h3>Context compounds</h3></div><span className="evolution-legend"><i /> before <i /> now</span></div><p className="evolution-intro">Your profile gets more precise as Bob combines the skill upload, repository map, company docs, and assessment answers.</p><div className="evolution-chart">{twin.evolution.map((item) => <div className="evolution-row" key={item.label}><span>{item.label}</span><div className="evolution-lanes"><i style={{ width: `${item.before}%` }} /><b style={{ width: `${item.after}%` }} /></div><strong>{item.after}%</strong></div>)}</div></section>
  </div>;
}
